{{- if .Values.monitoring.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nhi-testbed.componentName" (list . "grafana") }}
  namespace: {{ include "nhi-testbed.namespace" . }}
  labels:
    {{- include "nhi-testbed.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.monitoring.grafana.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "nhi-testbed.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
{{- end }}
