{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "nhi-testbed.namespace" . }}
  labels:
    {{- include "nhi-testbed.labels" . | nindent 4 }}
    nhi.testbed/purpose: "nhi-security-testbed"
{{- end }}
