{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nhi-testbed.componentName" (list . "api") }}
  namespace: {{ include "nhi-testbed.namespace" . }}
  labels:
    {{- include "nhi-testbed.labels" . | nindent 4 }}
    app.kubernetes.io/component: nhi-api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "nhi-testbed.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nhi-api
{{- end }}
