{{- if .Values.mockServices.vault.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nhi-testbed.componentName" (list . "vault") }}
  namespace: {{ include "nhi-testbed.namespace" . }}
  labels:
    {{- include "nhi-testbed.labels" . | nindent 4 }}
    app.kubernetes.io/component: vault
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.mockServices.vault.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "nhi-testbed.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: vault
{{- end }}
