# Wazuh Certificate Configuration
# Used by wazuh-certs-generator to create SSL certificates

nodes:
  # Wazuh indexer nodes
  indexer:
    - name: wazuh.indexer
      ip: 127.0.0.1

  # Wazuh server nodes
  server:
    - name: wazuh.manager
      ip: 127.0.0.1

  # Wazuh dashboard nodes
  dashboard:
    - name: wazuh.dashboard
      ip: 127.0.0.1
